services:
  csnotes:
    image: ghcr.io/warwickcsnotes/warwickcsnotes:latest
    container_name: warwickcsnotes
    environment:
      - VIRTUAL_HOST=csnotes
    ports:
      - 5422:3000
    restart: unless-stopped
    networks:
      - csnotes

networks:
  csnotes:
